name: ios_app_icon
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: ^3.6.0

dependencies:
  ext:
    git: 'https://github.com/lamtx/ext.git'
  image: ^4.0.6
  json_annotation: ^4.9.0
  path: ^1.8.0
  yaml: ^3.1.0
dev_dependencies:
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  test: ^1.16.0
